### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by lynvanbreen** [cmda-minor-vid/generative-art-20-21#1]
# 👋 Introduction

## Name

Lyn van Breen

## Class

VID1

## About me

Ik ben Lyn. Ik ben 22 jaar oud en kom van de opleiding Creative Business. In mijn vrije tijd game ik graag, maar ik ben ook dol op mode en make-up. Verder kijk ik graag (Koreaanse) series op Netflix! Mijn lievelingskleur is roze, wat overal om mij heen terug te zien is!

Ik kan lastig maar 1 favoriete emoji kiezen omdat ik ze heel graag gebruik. De eerste is 🥰 omdat het een warm en liefdevol gevoel overbrengt. De tweede is 🎀 omdat het lekker girly is en roze. Vind 'm gewoon erg mooi!
## Skill

Ik kan een beetje coden. Ben er wel voldoende bekend mee. Voordat ik aan Creative Business begon heb ik een jaar Informatica gestudeerd. Het bleek niet helemaal voor mij te zijn aangezien ik mijn creativiteit er niet voldoende in kwijt kon en niet overweg kon met Java. Wel kan ik het een en ander in HTML, CSS en JQuery Mobile! Dingen met websites gaat dus prima, maar full on programmeren van software is 'm niet helemaal. 😉

## GitHub repository

https://lynvanbreen.github.io/generative-art/

**Comment by dandevri** [comment]
👋 Lyn, thanks voor je GitHub link! Wat is je favoriete serie op Netflix? 🎀
