### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by FvanDoesum** [cmda-minor-vid/generative-art-20-21#10]
# 👋 Introduction

## Name
(Jose)Fien van Doesum

## Class
Vid2A

## About me

Hi! Ik zit in mijn derde jaar Creative Business en heb de specialisaties digitale media en mediaconcepting gedaan. Om mijn kennis te verbreden ben ik deze minor gaan volgen aan de opleiding CMD. Heel blij met deze keus want ik leer elke keer ontzettend veel nieuwe dingen! Ik ben altijd nieuwsgierig naar meer en doe graag met veel enthousiasme aan de werkcolleges mee.

Mijn favoriete emoties zijn 😛, 🙌 en 🥰 omdat ik graag mensen plaag en het erna weer goed wil/moet maken.

## Skill

Ik heb voor deze minor nog nooit iets gedaan met coding. Enkel hetgeen wat ik tijdens Webtypografie heb geleerd kan ik nu (een beetje 😅). Dus vooral CSS. Maarrr YouTube en Google zijn mijn beste vrienden.

## GitHub repository
https://github.com/FvanDoesum/Generative-Art

**Comment by dandevri** [comment]
Thanks! 🎉
