### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by davidvanr21** [cmda-minor-vid/generative-art-20-21#11]
# 👋 Introduction

Hi there! I'm David, 20 years old and following the minor Visual Interface Design. Generative Art is part of this minor. We're going experiment with abstract art, made with code. A super interesting course which will be very challenging but nice to experiment with.

## Name

David van Rumpt

## Class

VID1B

## About me

Obsessed with motion and great user-friendly design. Mostly working on visual projects, but love the challenge to work on code projects. Also freelancer since last month 🎉 #proud #yeah 

## Skill

I always think that it well be allright and that I've got everything under control. But I always find out there are a lot of hard things in writing code. Still struggling, but I like the process.

## GitHub repository

[Repository](https://github.com/davidvanr21/generative-art) / [Online project link](https://davidvanr21.github.io/generative-art/) / [Wiki project](https://github.com/davidvanr21/generative-art/wiki)

**Comment by dandevri** [comment]
Thanks! 🎉
