### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by nancy-herwegh** [cmda-minor-vid/generative-art-20-21#16]
# 👋 Introduction

## Name

Nancy Herwegh
## Class

VID1a
## About me

Hi, ik ben Nancy en ik kom van de opleiding Creative Business. Verder hou ik van alles wat tijdens corona niet kan; naar de bioscoop gaan, uiteten en festivals/concerten bezoeken. Ik haal m'n energie en positieve vibes uit muziek, daarom wil ik daar wat mee gaan doen voor deze opdracht.

😌, omdat 'ie blij en schattig is en kalmte uitstraalt.
## Skill

Ik zit nog in de beginnersfase.

## GitHub repository

https://github.com/nancy-herwegh/generative-art

**Comment by dandevri** [comment]
Thanks! 🎉
