### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by lunamaryse** [cmda-minor-vid/generative-art-20-21#18]
# 👋 Introduction

## Name
Luna de Fauw

## Class
VID1

## About me

Hey, ik ben Luna. Ik kom van de prachtige Veluwe en ben 20 jaar oud. Ik wil graag webdesigner / UX-designer worden. 

 🙂 omdat je niet weet of hij, blij, boos of teleurgesteld is. 

## Skill

Ik kan er niet omheen draaien, ik ben echt slecht in coderen. Ik wil het graag leren, maar pik het niet zo snel op. 

## GitHub repository
https://github.com/lunamaryse/generative.art.git

**Comment by dandevri** [comment]
Thanks! 🎉
