### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Kaylee-H** [cmda-minor-vid/generative-art-20-21#2]
# 👋 Introduction

## Name

Kaylee Heilijgers

## Class

VID 1
## About me

Hi, mijn naam is Kaylee. Ik kom van de opleding Creative Business. Ik heb een passie voor beeld en fotografie. Daarbij ben ik grafisch vormgever en hou ik van ontwerpen. Dit wil ik specialiseren in digitale producten. In mijn vrije tijd ben ik bezig met het ontwikkelen van een Indisch kookboek van mijn familierecepten. Ik heb al een familie-variant gemaakt, maar nu maak ik er een om te verkopen.

Dit is mijn favo emoji 🙃. Ik gebruik hem vaak bij sarcastische grappen/opmerkingen, omdat hij wel lacht maar net een eigen draai heeft. Ik vind het grappig dat hij anders is dan de andere emoji's. 

## Skill

Tijdens mijn vorige opleiding, MBO grafisch vormgeving, heb ik kennis gemaakt met coderen. Alleen merkte ik tijdens het vak webtypografie dat dit weg gezakt is. De codes kan ik lezen, maar bij het maken heb ik nog wat moeite. Wel was webtypografie een goede opstart om te leren coderen, ik kan dus alleen de basis.

## GitHub repository

https://github.com/Kaylee-H/generative-art

**Comment by dandevri** [comment]
👋 Kaylee, thanks voor je GitHub link! Welk indisch recept moet ik echt gaan maken? 🙃
