### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Abdelrahman-CMD** [cmda-minor-vid/generative-art-20-21#3]
# 👋 Introduction

## Name
Abdelrahman

## Class
VID2-B

## About me

Ik volg de opleiding CMD en zit in mijn derde leerjaar. Ik ben 26 jaar en woon in Amsterdam. Ik werk hiernaast 25 uur in de week bij de Jumbo als teamleider. 24/7 on the go heb bijna nooit vrije tijd.

:laughing: Ik ga vaak stuk om anderen of laat mensen stuk gaan van het lachen.
## Skill
Mijn hobby's zijn gamen, digital art, ui/ux design.

Beginner. Ik kan niet no look coderen, ben echt iemand die duizend tabbladen open heeft staan om alleen 1 regel code te snappen en te schrijven.
## GitHub repository
https://github.com/Abdelrahman-CMD/generative-art.git

**Comment by dandevri** [comment]
👋 Abdelrahman, thanks voor je GitHub link! Welke game speel je het liefst? 😆
