### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by MargotStrobbe** [cmda-minor-vid/generative-art-20-21#4]
# 👋 Introduction

## Name
Margot 

## Class
VID1

## About me
Mijn naam is Margot en ik volg de opleiding Creative Business. Ik ben 22 jaren jong en ik ben de trotse eigenaar van mijn 22 jarige groene Opel Corsa. Ik cross regelmatig de Afsluitdijk over en verblijf dan in Leeuwarden. 

😜 is mijn favoriete emoji. Waarom? Omdat het heel vaak mijn mood visualiseert en een hoop gedonder scheelt in mijn appjes.  

## Skill

In de opleiding CB heb ik welgeteld één keer een korte uitleg gehad over html en css. Tijdens Webtypografie in het eerste blok heb ik een sprintje getrokken en ik kan de weg nu wel aardig vinden. Ik weet wel dat dit weer een giga uitdaging gaat worden, maar gelukkig is Google mijn best friend.

## GitHub repository
https://github.com/MargotStrobbe/generative-art

**Comment by dandevri** [comment]
👋 Margot, thanks voor je GitHub link! 😜
