### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Joelkenneth** [cmda-minor-vid/generative-art-20-21#5]
# 👋 Introduction

## Name
Joël Jansen

## Class
VID 2

## About me

Graphic Design, Surfing, Gaming, Beer 

 🤙 🤙 🤙

## Skill

HTML = Fine, CSS = Good, Javascript = 😢

## GitHub repository
https://github.com/Joelkenneth/generative-art

**Comment by dandevri** [comment]
👋 Joël , thanks voor je GitHub link! 🤙
