### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Alishasars** [cmda-minor-vid/generative-art-20-21#6]
# 👋 Introduction

## Name

Alisha
## Class

VID1B
## About me

Hoi! Ik ben Alisha, ik studeer CMD aan Avans Hogeschool in Den Bosch en woon in Amsterdam.

Emoji: 😏, omdat het van alles kan betekenen. Wat betekent het voor jou😏?
## Skill

Basis heb ik in de tweede ooit gehad, maar kan er niet veel meer van herinneren (JavaScript). 
## GitHub repository

https://alishasars.github.io/generative-art/

**Comment by dandevri** [comment]
👋 Alisha, thanks voor je GitHub Link! Als je al eens wat met processing hebt gedaan moet dit vak een peulenschil worden 😏
