### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by JornMeessen** [cmda-minor-vid/generative-art-20-21#7]
# 👋 Introduction

## Name
Jorn Meessen

## Class
VID2a

## About me
😁👱‍♂️🚴🏼‍♂️👨‍🎨👟 🎧✈️ 

en Ik studeer CMD aan de Haagse Hogeschool

## Skill
HTML =  good 👍,    CSS = good 👍,  Javascript = fine 👌

Ik heb al eens eerder gewerkt met processing (binnen een ander vak in mijn opleiding). Dat ging mij toe redelijk goed af, dus ik verwacht geen moeilijkheden. Ik vind het leuk om uitgedaagd te worden om mijn skills te verbeteren :wink:.

## GitHub repository
https://github.com/JornMeessen/generative-art-jornmeessen

**Comment by dandevri** [comment]
Thanks! 🎉
