### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by mikehov** [cmda-minor-vid/generative-art-20-21#8]
# 👋 Introduction

## Name
Mike Hovenier

## Class
VID1A

## About me

Ik ben Mike, studeer CMD op de Hogeschool van Amsterdam.
😂🤔🐐🐑 (geitjes en schaapjes zijn top)
Dat was hem.

## Skill

Heb blok-tech gedaan dus ergens is nog wel wat stof hiervan blijven hangen, denk alleen wel eerlijk gezegd dat veel kennis verloren is gegaan. :)
Kan overigens wel prima overweg met HTML en CSS.

## GitHub repository
https://github.com/mikehov

**Comment by dandevri** [comment]
Thanks! 🎉
