### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by LawrencePrins** [cmda-minor-vid/generative-art-20-21#9]
# 👋 Introduction

## Name
Lawrence

## Class
VID-2B

## About me
Ik studeer CMD op de Hogeschool van Amsterdam en ik vind het voornamelijk leuk om zoveel mogelijk visueel te werken. Momenteel werk ik bij een klein bedrijf als Online (content) marketeer.

## Skill
HTML en CSS ging mij altijd goed af (binnen de opleiding) met JS liep ik soms wel eens vast, maar gelukkig bestaat m'n grote vriend Google 🙃

## GitHub repository
https://lawrenceprins.github.io/generative-art/

**Comment by dandevri** [comment]
Thanks! 🎉
